sudo: true
os: linux
language: python

python:
    - "3.5"

env:
- ASSIGNMENT_REPO=https://github.com/tgteacher/BigData-LA1.git

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install pyspark
  - pip install pytest
  # The two lines below ensure that everybody will run the same tests in
  # case they are updated
  - \mv -f tests tests.old
  - mkdir vanilla_tests && (cd vanilla_tests ; git clone $ASSIGNMENT_REPO )

script:
 - export PYTHONHASHSEED=0
 - export PYTHONPATH=$PYTHONPATH:`pwd`/answers
 - pytest -q vanilla_tests

after_success:
  - echo "success"

after_failure:
  - echo "failure"
