sudo: true
os: linux
language: python
python:
    - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install pyspark
  - pip install pytest
script:
 - export PYTHONHASHSEED=0
 - pytest -q tests/test_count*.py tests/test_parks*.py tests/test_uniq*.py

after_success:
  - echo "success"
after_failure:
  - echo "failure"
