sudo: true
os: linux
language: python
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y python3
  - pip install pyspark
  - pip install pytest
script:
 - pytest -m run_test.py

after_success:
  - echo "success"
after_failure:
  - echo "failure"
