sudo: true
os: linux
language: python
python:
    - "3.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y python3
  - pip install pyspark
  - pip install pytest
script:
 - ls
 - pwd
 - pytest -q tests/test_canard.py

after_success:
  - echo "success"
after_failure:
  - echo "failure"
